name: Provison infrastructure
run-name: |
  ${{github.actor}} : ${{github.event.head_commit.message}}
on: [push,workflow_dispatch]
jobs:
  Provison:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: terraform init
    